[package]
name = "my_dapp"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='3eb0b9b43f608644437522732ac21c8ac3ad59ab3e0d8ff3f364fdade9ee6722'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
