[package]
name = "randoom"
version = "1.0.0"
authors = []

[addresses]
cccy = "d9a2ded3fa92dc9062d381c51530e936376dfddd37611af6aa27e44a7978dda7"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
