[package]
name = "randoom"
version = "1.0.0"
authors = []

[addresses]
cccy = ""
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
