[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr = "0x0a442ebb9976a0c795ca9684e020fed4e52463bd8beed607b7f29d085822c8ce"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
