[package]
name = 'my_todo_list'
version = '1.0.0'
[dependencies.AptosFramework]
git = 'https://gitee.com/WGB5445/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-framework'
[addresses]
todolist_addr="_"