[package]
name = "myNftMarket"
version = "1.0.0"
authors = []

[addresses]
#me = "0x42"
me = "_"
[dev-addresses]

[dependencies]
AptosFramework = { local = "../../aptos-core/aptos-move/framework/aptos-framework" }
AptosTokenObjects = { local = "../../aptos-core/aptos-move/framework/aptos-token-objects" }

[dev-dependencies]

